alter table PROPOSALS_PROPOSAL alter column RESPONSIBLE_ID rename to RESPONSIBLE_ID__U94759 ^
alter table PROPOSALS_PROPOSAL alter column RESPONSIBLE_ID__U94759 set null ;
alter table PROPOSALS_PROPOSAL drop constraint FK_PROPOSALS_PROPOSAL_ON_RESPONSIBLE ;
drop index IDX_PROPOSALS_PROPOSAL_ON_RESPONSIBLE ;
